name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    name: Run CI/CD tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CI/CD tests 
        uses: akto-api-security/run-scan@v1.0.3
        with:
          AKTO_DASHBOARD_URL: ${{ secrets.AKTO_DASHBOARD_URL }}
          AKTO_API_KEY: ${{ secrets.AKTO_API_KEY }}
          AKTO_TEST_ID: ${{ secrets.AKTO_TEST_ID }}
          # START_TIME_DELAY: 180
